/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package tte;

import fungsi.akses;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.BorderLayout;
import java.awt.Cursor;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.URLEncoder;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JRViewer;
import okhttp3.*;

/**
 *
 * @author Victus
 */
public class FormTTE extends javax.swing.JDialog {
    private Connection koneksi=koneksiDB.condb();
    private sekuel Sequel=new sekuel();
    private validasi Valid=new validasi();
    private PreparedStatement ps;
    private ResultSet rs;
    private String no_rawat = "", tanggal = "", jenis_tte="", status_tte="false", no_surat="";
    private JasperPrint jprint;
    private static final Properties prop = new Properties(); 
    private String export_path="", authorization="";
    /**
     * Creates new form FormTTE
     */
    public FormTTE(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            prop.loadFromXML(new FileInputStream("setting/database.xml"));
            // export_path = prop.getProperty("EXPORTPDFRESUMEMEDISRALAN");
            export_path = Sequel.cariIsi("SELECT config.nilai_config FROM config WHERE config.id_config = '1'");
            // authorization = prop.getProperty("TTEAUTHORIZATION");
            authorization = Sequel.cariIsi("SELECT config.nilai_config FROM config WHERE config.id_config = '2'");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FormTTE.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FormTTE.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_nik = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_passphrase = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jInternalFrame1.setBackground(new java.awt.Color(255, 255, 255));
        jInternalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder("TTE"));
        jInternalFrame1.setForeground(new java.awt.Color(255, 255, 255));
        jInternalFrame1.setVisible(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 400));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 418));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("NIK");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 20));
        jPanel1.add(txt_nik, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 270, -1));

        jLabel2.setText("Passphrase");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 80, 20));
        jPanel1.add(txt_passphrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 270, -1));

        jButton1.setText("Proses TTE");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, -1, -1));

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        jInternalFrame1.getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jInternalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        switch (jenis_tte) {
            case "resume_medis_ralan":
                proses_tte("resume_medis_ralan_", "Tes");
                if (status_tte == "true") {
                    try {
                        // Update ke database
                        ps=koneksi.prepareStatement("UPDATE resume_pasien\n" +
                                "SET resume_pasien.status = 'Proses Tanda Tangan Elektronik Selesai'\n" +
                                "WHERE resume_pasien.no_rawat = '"+no_rawat+"';");
                        ps.executeUpdate();
                    } catch (SQLException ex) {
                        Logger.getLogger(FormTTE.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                break;
            case "surat_keterangan_sehat":
                proses_tte("surat_keterangan_sehat_", "Tes");
                if (status_tte == "true") {
                    try {
                        // Update ke database
                        ps=koneksi.prepareStatement("UPDATE surat_keterangan_sehat\n" +
                                "SET surat_keterangan_sehat.status = 'Proses Tanda Tangan Elektronik Selesai'\n" +
                                "WHERE surat_keterangan_sehat.no_rawat = '"+no_rawat+"' AND surat_keterangan_sehat.no_surat = '"+no_surat+"';");
                        ps.executeUpdate();
                    } catch (SQLException ex) {
                        Logger.getLogger(FormTTE.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormTTE dialog = new FormTTE(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField txt_nik;
    private javax.swing.JTextField txt_passphrase;
    // End of variables declaration//GEN-END:variables

    public void tampil_resume_medis_ralan() throws JRException{
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();

        Map<String, Object> param = new HashMap<>();    
        param.put("namars",akses.getnamars());
        param.put("alamatrs",akses.getalamatrs());
        param.put("kotars",akses.getkabupatenrs());
        param.put("propinsirs",akses.getpropinsirs());
        param.put("kontakrs",akses.getkontakrs());
        param.put("emailrs",akses.getemailrs());   
        param.put("logo",Sequel.cariGambar("select setting.logo from setting")); 
        param.put("norawat",no_rawat);
        if(Sequel.cariIsi("select reg_periksa.status_lanjut from reg_periksa where reg_periksa.no_rawat=?",no_rawat).equals("Ralan")){
            param.put("ruang",Sequel.cariIsi("select poliklinik.nm_poli from poliklinik inner join reg_periksa on reg_periksa.kd_poli=poliklinik.kd_poli where reg_periksa.no_rawat=?",no_rawat));
            tanggal=Sequel.cariIsi("select DATE_FORMAT(tgl_registrasi, '%d-%m-%Y') from reg_periksa where no_rawat=?",no_rawat);
            param.put("tanggalkeluar",tanggal);
        }else{
            param.put("ruang",Sequel.cariIsi("select nm_bangsal from bangsal inner join kamar inner join kamar_inap on bangsal.kd_bangsal=kamar.kd_bangsal and kamar_inap.kd_kamar=kamar.kd_kamar where no_rawat=? order by tgl_masuk desc limit 1 ",no_rawat));
            tanggal=Sequel.cariIsi("select DATE_FORMAT(tgl_keluar, '%d-%m-%Y') from kamar_inap where no_rawat=? order by tgl_keluar desc limit 1 ",no_rawat);
            param.put("tanggalkeluar",tanggal);
        }
        String finger=Sequel.cariIsi("select sha1(sidikjari.sidikjari) from sidikjari inner join pegawai on pegawai.id=sidikjari.id where pegawai.nik=?",txt_nik.getText());
        String nama_dokter = Sequel.cariIsi("SELECT pegawai.nama FROM pegawai WHERE pegawai.no_ktp = '"+txt_nik.getText()+"'");
        String kd_dokter = Sequel.cariIsi("SELECT pegawai.nik FROM pegawai WHERE pegawai.no_ktp = '"+txt_nik.getText()+"'");
        param.put("finger","Dikeluarkan di "+akses.getnamars()+", Kabupaten/Kota "+akses.getkabupatenrs()+"\nDitandatangani secara elektronik oleh "+nama_dokter+"\nID "+(finger.equals("")?kd_dokter:finger)+"\n"+tanggal); 

        // Valid.MyReport("rptLaporanResume.jasper","report","::[ Laporan Resume Pasien ]::",param);


        Properties systemProp = System.getProperties();

        // Ambil current dir
        String currentDir = systemProp.getProperty("user.dir");
        System.out.println("currentDir: "+currentDir);

        File dir = new File(currentDir);

        File fileRpt;
        String fullPath = "";
        if (dir.isDirectory()) {
            String[] isiDir = dir.list();
            for (String iDir : isiDir) {
                String path = currentDir + File.separatorChar + iDir + File.separatorChar + "rptLaporanResume.jasper";
                System.out.println("fullPath: "+path);
                fileRpt = new File(path);
                if (fileRpt.isFile()) { // Cek apakah file rpt.jrxml ada
                    fullPath = fileRpt.toString();
                    System.out.println("Found Report File at : " + fullPath);
                } // end if
            } // end for i
        } // end if

        PreparedStatement ps_rsdt;
        try {
            ps_rsdt = koneksi.prepareStatement("select \n" +
                                                "  reg_periksa.tgl_registrasi, \n" +
                                                "  reg_periksa.no_rawat, \n" +
                                                "  reg_periksa.no_rkm_medis, \n" +
                                                "  pasien.nm_pasien, \n" +
                                                "  pasien.jk, \n" +
                                                "  pasien.tgl_lahir, \n" +
                                                "  reg_periksa.umurdaftar, \n" +
                                                "  reg_periksa.sttsumur, \n" +
                                                "  pasien.pekerjaan, \n" +
                                                "  concat(\n" +
                                                "    pasien.alamat, ', ', kelurahan.nm_kel, \n" +
                                                "    ', ', kecamatan.nm_kec, ', ', kabupaten.nm_kab, \n" +
                                                "    ', ', propinsi.nm_prop\n" +
                                                "  ) as alamat, \n" +
                                                "  resume_pasien.kd_dokter, \n" +
                                                "  dokter.nm_dokter, \n" +
                                                "  resume_pasien.kondisi_pulang, \n" +
                                                "  resume_pasien.keluhan_utama, \n" +
                                                "  resume_pasien.jalannya_penyakit, \n" +
                                                "  resume_pasien.pemeriksaan_penunjang, \n" +
                                                "  resume_pasien.hasil_laborat, \n" +
                                                "  resume_pasien.diagnosa_utama, \n" +
                                                "  resume_pasien.kd_diagnosa_utama, \n" +
                                                "  resume_pasien.diagnosa_sekunder, \n" +
                                                "  resume_pasien.kd_diagnosa_sekunder, \n" +
                                                "  resume_pasien.diagnosa_sekunder2, \n" +
                                                "  resume_pasien.kd_diagnosa_sekunder2, \n" +
                                                "  resume_pasien.diagnosa_sekunder3, \n" +
                                                "  resume_pasien.kd_diagnosa_sekunder3, \n" +
                                                "  resume_pasien.diagnosa_sekunder4, \n" +
                                                "  resume_pasien.kd_diagnosa_sekunder4, \n" +
                                                "  resume_pasien.prosedur_utama, \n" +
                                                "  resume_pasien.kd_prosedur_utama, \n" +
                                                "  resume_pasien.prosedur_sekunder, \n" +
                                                "  resume_pasien.kd_prosedur_sekunder, \n" +
                                                "  resume_pasien.prosedur_sekunder2, \n" +
                                                "  resume_pasien.kd_prosedur_sekunder2, \n" +
                                                "  resume_pasien.prosedur_sekunder3, \n" +
                                                "  resume_pasien.kd_prosedur_sekunder3, \n" +
                                                "  resume_pasien.obat_pulang,\n" +
                                                "  resume_pasien.status,\n" +
                                                "  resume_pasien.created_at,\n" +
                                                "  resume_pasien.updated_at \n" +
                                                "from \n" +
                                                "  resume_pasien \n" +
                                                "  inner join reg_periksa on resume_pasien.no_rawat = reg_periksa.no_rawat \n" +
                                                "  inner join pasien on reg_periksa.no_rkm_medis = pasien.no_rkm_medis \n" +
                                                "  inner join dokter on resume_pasien.kd_dokter = dokter.kd_dokter \n" +
                                                "  inner join kelurahan on pasien.kd_kel = kelurahan.kd_kel \n" +
                                                "  inner join kecamatan on pasien.kd_kec = kecamatan.kd_kec \n" +
                                                "  inner join kabupaten on pasien.kd_kab = kabupaten.kd_kab \n" +
                                                "  inner join propinsi on pasien.kd_prop = propinsi.kd_prop \n" +
                                                "where \n" +
                                                "  resume_pasien.no_rawat = '"+no_rawat+"'");
            ResultSet rs_rsdt = ps_rsdt.executeQuery();

            JRResultSetDataSource rsdt = new JRResultSetDataSource(rs_rsdt);
            
            jprint = JasperFillManager.fillReport(fullPath, param, rsdt);
            JRViewer v = new JRViewer(jprint);
            jPanel2.setLayout(new BorderLayout());
            jPanel2.add(v);
        } catch (SQLException ex) {
            Logger.getLogger(FormTTE.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void tampil_surat_keterangan_sehat() throws JRException{
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();

        Map<String, Object> param = new HashMap<>();    
        param.put("namars",akses.getnamars());
        param.put("alamatrs",akses.getalamatrs());
        param.put("kotars",akses.getkabupatenrs());
        param.put("propinsirs",akses.getpropinsirs());
        param.put("kontakrs",akses.getkontakrs());
        param.put("emailrs",akses.getemailrs());   
        param.put("logo",Sequel.cariGambar("select setting.logo from setting")); 
        String kodedokter=Sequel.cariIsi("select reg_periksa.kd_dokter from reg_periksa where reg_periksa.no_rawat=?",no_rawat);
        String namadokter=Sequel.cariIsi("select dokter.nm_dokter from dokter where dokter.kd_dokter=?",kodedokter);
        String finger=Sequel.cariIsi("select sha1(sidikjari.sidikjari) from sidikjari inner join pegawai on pegawai.id=sidikjari.id where pegawai.nik=?",kodedokter);
        param.put("finger","Dikeluarkan di "+akses.getnamars()+", Kabupaten/Kota "+akses.getkabupatenrs()+"\nDitandatangani secara elektronik oleh "+namadokter+"\nID "+(finger.equals("")?kodedokter:finger)+"\n"+Sequel.cariIsi("select DATE_FORMAT(reg_periksa.tgl_registrasi,'%d-%m-%Y') from reg_periksa where reg_periksa.no_rawat=?",no_rawat)); 

        Properties systemProp = System.getProperties();

        // Ambil current dir
        String currentDir = systemProp.getProperty("user.dir");
        System.out.println("currentDir: "+currentDir);

        File dir = new File(currentDir);

        File fileRpt;
        String fullPath = "";
        if (dir.isDirectory()) {
            String[] isiDir = dir.list();
            for (String iDir : isiDir) {
                String path = currentDir + File.separatorChar + iDir + File.separatorChar + "rptSuratKeteranganSehat.jasper";
                System.out.println("fullPath: "+path);
                fileRpt = new File(path);
                if (fileRpt.isFile()) { // Cek apakah file rpt.jrxml ada
                    fullPath = fileRpt.toString();
                    System.out.println("Found Report File at : " + fullPath);
                } // end if
            } // end for i
        } // end if

        PreparedStatement ps_rsdt;
        try {
            ps_rsdt = koneksi.prepareStatement("select "+
                                                "  surat_keterangan_sehat.no_surat, "+
                                                "  DATE_FORMAT("+
                                                "    surat_keterangan_sehat.tanggalsurat, "+
                                                "    '%d-%m-%Y'"+
                                                "  ) as tanggalsurat, "+
                                                "  surat_keterangan_sehat.berat, "+
                                                "  surat_keterangan_sehat.tinggi, "+
                                                "  surat_keterangan_sehat.tensi, "+
                                                "  surat_keterangan_sehat.suhu, "+
                                                "  surat_keterangan_sehat.nadi, "+
                                                "  surat_keterangan_sehat.bmi, "+
                                                "  surat_keterangan_sehat.butawarna, "+
                                                "  reg_periksa.no_rkm_medis,surat_keterangan_sehat.keperluan, "+
                                                "  DATE_FORMAT(pasien.tgl_lahir, '%d-%m-%Y') as tgl_lahir, "+
                                                "  surat_keterangan_sehat.kesimpulan, "+
                                                "  dokter.nm_dokter, "+
                                                "  UCASE(pasien.jk) AS jk, "+
                                                "  reg_periksa.kd_dokter, "+
                                                "  pasien.nm_pasien, "+
                                                "  concat("+
                                                "    reg_periksa.umurdaftar, ' ', reg_periksa.sttsumur"+
                                                "  ) as umur, "+
                                                "  UCASE(concat("+
                                                "    pasien.alamat, ', ', kelurahan.nm_kel, "+
                                                "    ', ', kecamatan.nm_kec, ', ', kabupaten.nm_kab"+
                                                "  )) as alamat "+
                                                "from "+
                                                "  surat_keterangan_sehat "+
                                                "  inner join reg_periksa "+
                                                "  inner join pasien "+
                                                "  inner join dokter "+
                                                "  inner join kelurahan "+
                                                "  inner join kecamatan "+
                                                "  inner join kabupaten on reg_periksa.no_rkm_medis = pasien.no_rkm_medis "+
                                                "  and reg_periksa.kd_dokter = dokter.kd_dokter "+
                                                "  and pasien.kd_kel = kelurahan.kd_kel "+
                                                "  and pasien.kd_kec = kecamatan.kd_kec "+
                                                "  and pasien.kd_kab = kabupaten.kd_kab "+
                                                "  and reg_periksa.no_rawat = surat_keterangan_sehat.no_rawat"+
                                              " where reg_periksa.no_rawat='"+no_rawat+"' and surat_keterangan_sehat.no_surat='"+no_surat+"' ");
            System.out.println("query surat sehat: "+ps_rsdt.toString());
            ResultSet rs_rsdt = ps_rsdt.executeQuery();

            JRResultSetDataSource rsdt = new JRResultSetDataSource(rs_rsdt);
            
            jprint = JasperFillManager.fillReport(fullPath, param, rsdt);
            JRViewer v = new JRViewer(jprint);
            jPanel2.setLayout(new BorderLayout());
            jPanel2.add(v);
        } catch (SQLException ex) {
            Logger.getLogger(FormTTE.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void proses_tte(String nama_depan_file, String link_qr){
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        // Export to PDF
        String nama_file_export = export_path+nama_depan_file+no_rawat.replace("/", "_")+".pdf";
        String nama_file = nama_depan_file+no_rawat.replace("/", "_")+".pdf";
        String nama_file_signed = export_path+nama_depan_file+no_rawat.replace("/", "_")+"_signed.pdf";
        Path path = Paths.get(nama_file_export);
        System.out.println("nama_file_export: "+nama_file_export);

        // Export to PDF
        if (Files.notExists(path)) {
            // file is not exist
            System.out.println("file is not exist: ");
            try {
                JasperExportManager.exportReportToPdfFile(jprint, nama_file_export);
            } catch (JRException ex) {
                Logger.getLogger(FormTTE.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            System.out.println("file is exist: ");
        }
        
        OkHttpClient client = new OkHttpClient().newBuilder().build();

        RequestBody fileBody = RequestBody.create(
            MediaType.parse("application/pdf"),
            new File(nama_file_export) // Pastikan path benar dan file ada
        );

        RequestBody body = new MultipartBody.Builder().setType(MultipartBody.FORM)
            .addFormDataPart("file", nama_file, fileBody) // Pastikan nama file sesuai
            .build();

        Request request = new Request.Builder()
            .url("http://103.162.72.108/api/sign/pdf?nik="+txt_nik.getText()+"&passphrase="+txt_passphrase.getText()+"&tampilan=visible&image=false&linkQR="+link_qr+"&halaman=TERAKHIR&yAxis=43&xAxis=28&width=550&height=130&text=Dokumen%20ini%20ditandatangani%20secara%20elektronik")
            .method("POST", body)
            .addHeader("Authorization", "Basic "+authorization+"")
            .build();

        try {
            Response response = client.newCall(request).execute();

            if (response.isSuccessful() && response.body() != null) {
                // Simpan PDF ke file lokal
                InputStream inputStream = response.body().byteStream();
                File outputFile = new File(nama_file_signed); // Lokasi file output
                FileOutputStream fileOutputStream = new FileOutputStream(outputFile);

                byte[] buffer = new byte[4096];
                int bytesRead;
                while ((bytesRead = inputStream.read(buffer)) != -1) {
                    fileOutputStream.write(buffer, 0, bytesRead);
                }

                fileOutputStream.close();
                inputStream.close();
                System.out.println("File berhasil disimpan ke: " + outputFile.getAbsolutePath());
                this.setCursor(Cursor.getDefaultCursor());
                status_tte = "true";
                JOptionPane.showMessageDialog(null, "File berhasil disimpan ke: " + outputFile.getAbsolutePath());
            } else {
                System.out.println("Gagal mendapatkan file. Kode: " + response.code());
                System.out.println("Pesan: " + response.message());
                status_tte = "false";
                this.setCursor(Cursor.getDefaultCursor());
                JOptionPane.showMessageDialog(null, "Gagal mendapatkan file. Kode: " + response.code() + "\n" + "Pesan: " + response.message());
            }
        } catch (IOException ex) {
            ex.printStackTrace();
            this.setCursor(Cursor.getDefaultCursor());
        }
    }
    
    public void setNoRawat(String no_rawat, String jenis_tte) {
        this.no_rawat = no_rawat;
        this.jenis_tte = jenis_tte;
        System.out.println("set no rawat: "+this.no_rawat+"\n"+"jenis tte: "+this.jenis_tte);
    }

    public void setNoSurat(String no_surat) {
        this.no_surat = no_surat;
    }
}
