/*
  Dilarang keras menggandakan/mengcopy/menyebarkan/membajak/mendecompile 
  Software ini dalam bentuk apapun tanpa seijin pembuat software
  (Khanza.Soft Media). Bagi yang sengaja membajak softaware ini ta
  npa ijin, kami sumpahi sial 1000 turunan, miskin sampai 500 turu
  nan. Selalu mendapat kecelakaan sampai 400 turunan. Anak pertama
  nya cacat tidak punya kaki sampai 300 turunan. Susah cari jodoh
  sampai umur 50 tahun sampai 200 turunan. Ya Alloh maafkan kami 
  karena telah berdoa buruk, semua ini kami lakukan karena kami ti
  dak pernah rela karya kami dibajak tanpa ijin.
 */


package keuangan;

import setting.*;
import fungsi.WarnaTable;
import fungsi.WarnaTableIDRG;
import fungsi.WarnaTablePenjaminan;
import fungsi.akses;
import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.validasi2;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import surat.SuratKeteranganSehat;

/**
 *
 * @author Christopher Nanda Jonathan the greatest IT in the world ever
 */
public class DlgIDRG extends javax.swing.JDialog {
    private final DefaultTableModel tabMode, tabMode2;
    private Connection koneksi=koneksiDB.condb();
    private sekuel Sequel=new sekuel();
    private validasi2 Valid=new validasi2();
    private ResultSet rs;
    // private ResultSet rs_satu_sehat_detail_pasien;
    private PreparedStatement ps;
    // private PreparedStatement ps_satu_sehat_detail_pasien;
    private int i=0;
    //private String village="",district="",city="",province="",village_pj="",district_pj="",city_pj="",province_pj="",detail_alamat_pasien="",
    //        detail_alamat_pj="",id_kel="",id_kec="",id_kab="",id_prov="",id_kel_pj="",id_kec_pj="",id_kab_pj="",id_prov_pj="",
    //        postal_code="",id_rw="",id_rt="",rw_pj="",rt_pj="",emergency_contact="";

    /** Creates new form DlgAdmin
     * @param parent
     * @param modal */
    public DlgIDRG(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation(10,10);
        setSize(457,249);

        Object[] row={
            "No Rawat",
            "Tgl Pendaftaran",
            "SEP",
            "Nota",
            "Surat",
            "RM",
            "Pasien",
            "Dokter",
            "Poli",
            "Pembayaran",
            "Status Lanjut",
            "Encounter",
            "Status Surat Kontrol",
            "Sudah Verifikasi",
            "Sudah Coding",
            "Sudah Compile"
        };
        tabMode=new DefaultTableModel(null,row){
              @Override public boolean isCellEditable(int rowIndex, int colIndex){return false;}
        };
        tbRalan.setModel(tabMode);
        tbRalan.setPreferredScrollableViewportSize(new Dimension(500,500));
        tbRalan.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        tbRalan.setDefaultRenderer(Object.class, new WarnaTableIDRG());
        
        
        Object[] row2={
            "No Rawat",
            "Tgl Keluar",
            "SEP",
            "Nota",
            "Surat",
            "RM",
            "Pasien",
            "DPJP",
            "Kamar",
            "Pembayaran",
            "Status Pulang",
            "Encounter",
            "Status Bayar",
            "Sudah Verifikasi",
            "Sudah Coding",
            "Sudah Compile"
        };
        tabMode2=new DefaultTableModel(null,row2){
              @Override public boolean isCellEditable(int rowIndex, int colIndex){return false;}
        };
        tbRanap.setModel(tabMode2);
        tbRanap.setPreferredScrollableViewportSize(new Dimension(500,500));
        tbRanap.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        tbRanap.setDefaultRenderer(Object.class, new WarnaTableIDRG());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu1 = new javax.swing.JMenu();
        sortSepAsc = new javax.swing.JMenuItem();
        sortSepDesc = new javax.swing.JMenuItem();
        sortSep = new javax.swing.JTextField();
        internalFrame1 = new widget.InternalFrame();
        panelGlass7 = new widget.panelisi();
        jLabel3 = new widget.Label();
        txtNoNota = new widget.TextBox();
        jLabel4 = new widget.Label();
        txtNoRm = new widget.TextBox();
        jLabel5 = new widget.Label();
        txtNorawat = new widget.TextBox();
        txtNoSurat = new widget.TextBox();
        jLabel7 = new widget.Label();
        jLabel8 = new widget.Label();
        txtSep = new widget.TextBox();
        jLabel21 = new widget.Label();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        panelGlass5 = new widget.panelisi();
        jLabel15 = new widget.Label();
        DTPCari1 = new widget.Tanggal();
        jLabel17 = new widget.Label();
        DTPCari2 = new widget.Tanggal();
        jLabel6 = new widget.Label();
        TCari = new widget.TextBox();
        jLabel12 = new widget.Label();
        cmbStatus = new widget.ComboBox();
        jLabel13 = new widget.Label();
        cmbStatusCompile = new widget.ComboBox();
        jLabel14 = new widget.Label();
        cmbStatusVerifikator = new widget.ComboBox();
        BtnCari = new widget.Button();
        BtnKeluar = new widget.Button();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Scroll = new widget.ScrollPane();
        tbRalan = new widget.Table();
        Scroll1 = new widget.ScrollPane();
        tbRanap = new widget.Table();

        jPopupMenu1.setName("jPopupMenu1"); // NOI18N

        jMenu1.setText("Sort Data");
        jMenu1.setName("jMenu1"); // NOI18N

        sortSepAsc.setText("Sorting SEP ASC");
        sortSepAsc.setName("sortSepAsc"); // NOI18N
        sortSepAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortSepAscActionPerformed(evt);
            }
        });
        jMenu1.add(sortSepAsc);

        sortSepDesc.setText("Sorting SEP DESC");
        sortSepDesc.setName("sortSepDesc"); // NOI18N
        sortSepDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortSepDescActionPerformed(evt);
            }
        });
        jMenu1.add(sortSepDesc);

        jPopupMenu1.add(jMenu1);

        sortSep.setText("ASC");
        sortSep.setName("sortSep"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Modul IDRG ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        panelGlass7.setName("panelGlass7"); // NOI18N
        panelGlass7.setPreferredSize(new java.awt.Dimension(44, 75));
        panelGlass7.setLayout(null);

        jLabel3.setText("No Nota");
        jLabel3.setName("jLabel3"); // NOI18N
        panelGlass7.add(jLabel3);
        jLabel3.setBounds(440, 10, 60, 23);

        txtNoNota.setHighlighter(null);
        txtNoNota.setName("txtNoNota"); // NOI18N
        txtNoNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoNotaActionPerformed(evt);
            }
        });
        txtNoNota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNoNotaKeyPressed(evt);
            }
        });
        panelGlass7.add(txtNoNota);
        txtNoNota.setBounds(510, 10, 250, 23);

        jLabel4.setText("No Surat");
        jLabel4.setName("jLabel4"); // NOI18N
        panelGlass7.add(jLabel4);
        jLabel4.setBounds(760, 10, 60, 23);

        txtNoRm.setName("txtNoRm"); // NOI18N
        txtNoRm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNoRmKeyPressed(evt);
            }
        });
        panelGlass7.add(txtNoRm);
        txtNoRm.setBounds(50, 10, 90, 24);

        jLabel5.setText("RM");
        jLabel5.setName("jLabel5"); // NOI18N
        panelGlass7.add(jLabel5);
        jLabel5.setBounds(10, 10, 30, 23);

        txtNorawat.setHighlighter(null);
        txtNorawat.setName("txtNorawat"); // NOI18N
        txtNorawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNorawatActionPerformed(evt);
            }
        });
        txtNorawat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNorawatKeyPressed(evt);
            }
        });
        panelGlass7.add(txtNorawat);
        txtNorawat.setBounds(220, 10, 220, 23);

        txtNoSurat.setName("txtNoSurat"); // NOI18N
        txtNoSurat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNoSuratKeyPressed(evt);
            }
        });
        panelGlass7.add(txtNoSurat);
        txtNoSurat.setBounds(840, 10, 230, 24);

        jLabel7.setText("No Rawat");
        jLabel7.setName("jLabel7"); // NOI18N
        panelGlass7.add(jLabel7);
        jLabel7.setBounds(140, 10, 70, 23);

        jLabel8.setText("SEP");
        jLabel8.setName("jLabel8"); // NOI18N
        panelGlass7.add(jLabel8);
        jLabel8.setBounds(1080, 10, 60, 23);

        txtSep.setName("txtSep"); // NOI18N
        txtSep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSepKeyPressed(evt);
            }
        });
        panelGlass7.add(txtSep);
        txtSep.setBounds(1160, 10, 230, 24);

        jLabel21.setText("Keterangan Warna :");
        jLabel21.setName("jLabel21"); // NOI18N
        jLabel21.setPreferredSize(new java.awt.Dimension(110, 23));
        panelGlass7.add(jLabel21);
        jLabel21.setBounds(440, 40, 110, 30);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(252, 227, 138));
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Sudah Coding & Belum Compile");
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jTextField1.setName("jTextField1"); // NOI18N
        jTextField1.setPreferredSize(new java.awt.Dimension(95, 20));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        panelGlass7.add(jTextField1);
        jTextField1.setBounds(770, 40, 200, 30);

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(149, 255, 211));
        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Sudah Coding & Sudah Compile");
        jTextField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jTextField2.setName("jTextField2"); // NOI18N
        jTextField2.setPreferredSize(new java.awt.Dimension(40, 20));
        panelGlass7.add(jTextField2);
        jTextField2.setBounds(980, 40, 200, 30);

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(0, 0, 0));
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("Belum Coding & Sudah Compile");
        jTextField3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jTextField3.setName("jTextField3"); // NOI18N
        jTextField3.setPreferredSize(new java.awt.Dimension(75, 20));
        panelGlass7.add(jTextField3);
        jTextField3.setBounds(1190, 40, 200, 30);

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(243, 129, 129));
        jTextField4.setForeground(new java.awt.Color(0, 0, 0));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("Belum Coding & Belum Compile");
        jTextField4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jTextField4.setName("jTextField4"); // NOI18N
        jTextField4.setPreferredSize(new java.awt.Dimension(90, 20));
        panelGlass7.add(jTextField4);
        jTextField4.setBounds(560, 40, 200, 30);

        internalFrame1.add(panelGlass7, java.awt.BorderLayout.PAGE_START);

        panelGlass5.setName("panelGlass5"); // NOI18N
        panelGlass5.setPreferredSize(new java.awt.Dimension(55, 55));
        panelGlass5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        jLabel15.setText("Periode :");
        jLabel15.setName("jLabel15"); // NOI18N
        jLabel15.setPreferredSize(new java.awt.Dimension(70, 23));
        panelGlass5.add(jLabel15);

        DTPCari1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "18-02-2026" }));
        DTPCari1.setDisplayFormat("dd-MM-yyyy");
        DTPCari1.setName("DTPCari1"); // NOI18N
        DTPCari1.setOpaque(false);
        DTPCari1.setPreferredSize(new java.awt.Dimension(90, 23));
        panelGlass5.add(DTPCari1);

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("s.d");
        jLabel17.setName("jLabel17"); // NOI18N
        jLabel17.setPreferredSize(new java.awt.Dimension(23, 23));
        panelGlass5.add(jLabel17);

        DTPCari2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "18-02-2026" }));
        DTPCari2.setDisplayFormat("dd-MM-yyyy");
        DTPCari2.setName("DTPCari2"); // NOI18N
        DTPCari2.setOpaque(false);
        DTPCari2.setPreferredSize(new java.awt.Dimension(90, 23));
        panelGlass5.add(DTPCari2);

        jLabel6.setText("Key Word :");
        jLabel6.setName("jLabel6"); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(70, 23));
        panelGlass5.add(jLabel6);

        TCari.setName("TCari"); // NOI18N
        TCari.setPreferredSize(new java.awt.Dimension(303, 23));
        TCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TCariKeyPressed(evt);
            }
        });
        panelGlass5.add(TCari);

        jLabel12.setText("Status Coding :");
        jLabel12.setName("jLabel12"); // NOI18N
        jLabel12.setPreferredSize(new java.awt.Dimension(100, 23));
        panelGlass5.add(jLabel12);

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Semua", "Belum", "Sudah" }));
        cmbStatus.setName("cmbStatus"); // NOI18N
        cmbStatus.setPreferredSize(new java.awt.Dimension(150, 23));
        panelGlass5.add(cmbStatus);

        jLabel13.setText("Status Compile :");
        jLabel13.setName("jLabel13"); // NOI18N
        jLabel13.setPreferredSize(new java.awt.Dimension(100, 23));
        panelGlass5.add(jLabel13);

        cmbStatusCompile.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Semua", "Belum", "Sudah" }));
        cmbStatusCompile.setName("cmbStatusCompile"); // NOI18N
        cmbStatusCompile.setPreferredSize(new java.awt.Dimension(150, 23));
        panelGlass5.add(cmbStatusCompile);

        jLabel14.setText("Status Verifikator :");
        jLabel14.setName("jLabel14"); // NOI18N
        jLabel14.setPreferredSize(new java.awt.Dimension(100, 23));
        panelGlass5.add(jLabel14);

        cmbStatusVerifikator.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Semua", "Belum", "Sudah" }));
        cmbStatusVerifikator.setName("cmbStatusVerifikator"); // NOI18N
        cmbStatusVerifikator.setPreferredSize(new java.awt.Dimension(150, 23));
        panelGlass5.add(cmbStatusVerifikator);

        BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCari.setMnemonic('6');
        BtnCari.setToolTipText("Alt+6");
        BtnCari.setName("BtnCari"); // NOI18N
        BtnCari.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });
        BtnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCariKeyPressed(evt);
            }
        });
        panelGlass5.add(BtnCari);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setIconTextGap(3);
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass5.add(BtnKeluar);

        internalFrame1.add(panelGlass5, java.awt.BorderLayout.PAGE_END);

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        tbRalan.setAutoCreateRowSorter(true);
        tbRalan.setToolTipText("Silahkan klik untuk memilih data yang mau diedit ataupun dihapus");
        tbRalan.setComponentPopupMenu(jPopupMenu1);
        tbRalan.setName("tbRalan"); // NOI18N
        tbRalan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbRalanMouseClicked(evt);
            }
        });
        tbRalan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbRalanKeyPressed(evt);
            }
        });
        Scroll.setViewportView(tbRalan);

        jTabbedPane1.addTab("Rawat Jalan", Scroll);

        Scroll1.setName("Scroll1"); // NOI18N
        Scroll1.setOpaque(true);

        tbRanap.setAutoCreateRowSorter(true);
        tbRanap.setToolTipText("Silahkan klik untuk memilih data yang mau diedit ataupun dihapus");
        tbRanap.setComponentPopupMenu(jPopupMenu1);
        tbRanap.setName("tbRanap"); // NOI18N
        tbRanap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbRanapMouseClicked(evt);
            }
        });
        tbRanap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbRanapKeyPressed(evt);
            }
        });
        Scroll1.setViewportView(tbRanap);

        jTabbedPane1.addTab("Rawat Inap", Scroll1);

        internalFrame1.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNoNotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoNotaKeyPressed
        
}//GEN-LAST:event_txtNoNotaKeyPressed

    private void txtNoRmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoRmKeyPressed
        
}//GEN-LAST:event_txtNoRmKeyPressed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
}//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        dispose();
}//GEN-LAST:event_BtnKeluarKeyPressed

    private void tbRalanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbRalanMouseClicked
        if(tabMode.getRowCount()!=0){
            try {
                if(evt.getClickCount()==1){
//                    i=tbNota.getSelectedColumn();
//                    if(i==0){
                        txtNorawat.setText(tbRalan.getValueAt(tbRalan.getSelectedRow(), 0).toString());
                        txtNoNota.setText(tbRalan.getValueAt(tbRalan.getSelectedRow(), 3).toString());
                        txtNoSurat.setText(tbRalan.getValueAt(tbRalan.getSelectedRow(), 4).toString());
                        txtNoRm.setText(tbRalan.getValueAt(tbRalan.getSelectedRow(), 5).toString());
                        txtSep.setText(tbRalan.getValueAt(tbRalan.getSelectedRow(), 2).toString());
//                    }
                }else if(evt.getClickCount()==2){
                    if(tbRalan.getRowCount()==0){
                        JOptionPane.showMessageDialog(null,"Maaf, data pasien sudah habis...!!!!");
                    }else if(txtNoRm.getText().trim().equals("")){
                        JOptionPane.showMessageDialog(null,"Maaf, Silahkan anda pilih dulu data registrasi pada table...!!!");
                        TCari.requestFocus();
                    }else{
                        if(tbRalan.getSelectedRow()!= -1){
                            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                            DlgIDRGProses proses=new DlgIDRGProses(null,false);
                            proses.emptTeks();
                            proses.setSize(internalFrame1.getWidth()-20,internalFrame1.getHeight()-20);
                            proses.setLocationRelativeTo(internalFrame1);
                            proses.setData(
                                    tbRalan.getValueAt(tbRalan.getSelectedRow(), 0).toString(),
                                    tbRalan.getValueAt(tbRalan.getSelectedRow(), 5).toString(),
                                    tbRalan.getValueAt(tbRalan.getSelectedRow(), 3).toString(),
                                    tbRalan.getValueAt(tbRalan.getSelectedRow(), 4).toString(),
                                    tbRalan.getValueAt(tbRalan.getSelectedRow(), 2).toString()
                            );
                            proses.setVisible(true);
                            this.setCursor(Cursor.getDefaultCursor());
                        }
                    }
                }
            } catch (java.lang.NullPointerException e) {
                System.out.println(e);
            }
        }
}//GEN-LAST:event_tbRalanMouseClicked

    private void tbRalanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbRalanKeyPressed
        if(tabMode.getRowCount()!=0){
            if((evt.getKeyCode()==KeyEvent.VK_ENTER)||(evt.getKeyCode()==KeyEvent.VK_UP)||(evt.getKeyCode()==KeyEvent.VK_DOWN)){
                try {
                    getData();
                } catch (java.lang.NullPointerException e) {
                }
            }
        }
}//GEN-LAST:event_tbRalanKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        emptTeks();
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        tampil();
    }//GEN-LAST:event_formWindowOpened

    private void txtNoNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoNotaActionPerformed

    private void txtNorawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNorawatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNorawatActionPerformed

    private void txtNorawatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNorawatKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNorawatKeyPressed

    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
        jTabbedPane1MouseClicked(null);
    }//GEN-LAST:event_BtnCariActionPerformed

    private void BtnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCariKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnCariActionPerformed(null);
        }else{
//            Valid.pindah(evt, TCari, BtnAll);
        }
    }//GEN-LAST:event_BtnCariKeyPressed

    private void TCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCariKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            BtnCariActionPerformed(null);
        }else if(evt.getKeyCode()==KeyEvent.VK_PAGE_DOWN){
            BtnCari.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_PAGE_UP){
            BtnKeluar.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_UP){
//            if(TabRawat.getSelectedIndex()==0){
//                tbKasirRalan.requestFocus();
//            }else if(TabRawat.getSelectedIndex()==1){
//                tbKasirRalan2.requestFocus();
//            }
        }
    }//GEN-LAST:event_TCariKeyPressed

    private void txtNoSuratKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoSuratKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoSuratKeyPressed

    private void sortSepAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortSepAscActionPerformed
        sortSep.setText("ASC");
        tampil();
    }//GEN-LAST:event_sortSepAscActionPerformed

    private void sortSepDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortSepDescActionPerformed
        sortSep.setText("DESC");
        tampil();
    }//GEN-LAST:event_sortSepDescActionPerformed

    private void txtSepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSepKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSepKeyPressed

    private void tbRanapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbRanapMouseClicked
        if(tabMode2.getRowCount()!=0){
            try {
                if(evt.getClickCount()==1){
//                    i=tbNota.getSelectedColumn();
//                    if(i==0){
                        txtNorawat.setText(tbRanap.getValueAt(tbRanap.getSelectedRow(), 0).toString());
                        txtNoNota.setText(tbRanap.getValueAt(tbRanap.getSelectedRow(), 3).toString());
                        txtNoSurat.setText(tbRanap.getValueAt(tbRanap.getSelectedRow(), 4).toString());
                        txtNoRm.setText(tbRanap.getValueAt(tbRanap.getSelectedRow(), 5).toString());
                        txtSep.setText(tbRanap.getValueAt(tbRanap.getSelectedRow(), 2).toString());
//                    }
                }else if(evt.getClickCount()==2){
                    if(tbRanap.getRowCount()==0){
                        JOptionPane.showMessageDialog(null,"Maaf, data pasien sudah habis...!!!!");
                    }else if(txtNoRm.getText().trim().equals("")){
                        JOptionPane.showMessageDialog(null,"Maaf, Silahkan anda pilih dulu data registrasi pada table...!!!");
                        TCari.requestFocus();
                    }else{
                        if(tbRanap.getSelectedRow()!= -1){
                            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                            DlgIDRGProses proses=new DlgIDRGProses(null,false);
                            proses.emptTeks();
                            proses.setSize(internalFrame1.getWidth()-20,internalFrame1.getHeight()-20);
                            proses.setLocationRelativeTo(internalFrame1);
                            proses.setData(
                                    tbRanap.getValueAt(tbRanap.getSelectedRow(), 0).toString(),
                                    tbRanap.getValueAt(tbRanap.getSelectedRow(), 5).toString(),
                                    tbRanap.getValueAt(tbRanap.getSelectedRow(), 3).toString(),
                                    tbRanap.getValueAt(tbRanap.getSelectedRow(), 4).toString(),
                                    tbRanap.getValueAt(tbRanap.getSelectedRow(), 2).toString()
                            );
                            proses.setVisible(true);
                            this.setCursor(Cursor.getDefaultCursor());
                        }
                    }
                }
            } catch (java.lang.NullPointerException e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_tbRanapMouseClicked

    private void tbRanapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbRanapKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbRanapKeyPressed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        if(jTabbedPane1.getSelectedIndex()==0){
            System.out.println("tampil ralan");
            tabMode.setRowCount(0);
            tampil();
        }else if(jTabbedPane1.getSelectedIndex()==1){
            System.out.println("tampil ranap");
            tabMode2.setRowCount(0);
            tampil_ranap();
        }
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgIDRG dialog = new DlgIDRG(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnCari;
    private widget.Button BtnKeluar;
    private widget.Tanggal DTPCari1;
    private widget.Tanggal DTPCari2;
    private widget.ScrollPane Scroll;
    private widget.ScrollPane Scroll1;
    private widget.TextBox TCari;
    private widget.ComboBox cmbStatus;
    private widget.ComboBox cmbStatusCompile;
    private widget.ComboBox cmbStatusVerifikator;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel12;
    private widget.Label jLabel13;
    private widget.Label jLabel14;
    private widget.Label jLabel15;
    private widget.Label jLabel17;
    private widget.Label jLabel21;
    private widget.Label jLabel3;
    private widget.Label jLabel4;
    private widget.Label jLabel5;
    private widget.Label jLabel6;
    private widget.Label jLabel7;
    private widget.Label jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private widget.panelisi panelGlass5;
    private widget.panelisi panelGlass7;
    private javax.swing.JTextField sortSep;
    private javax.swing.JMenuItem sortSepAsc;
    private javax.swing.JMenuItem sortSepDesc;
    private widget.Table tbRalan;
    private widget.Table tbRanap;
    private widget.TextBox txtNoNota;
    private widget.TextBox txtNoRm;
    private widget.TextBox txtNoSurat;
    private widget.TextBox txtNorawat;
    private widget.TextBox txtSep;
    // End of variables declaration//GEN-END:variables

    public void tampil() {
        Valid.tabelKosong(tabMode);
        try{
            String date_1 = Valid.SetTgl(DTPCari1.getSelectedItem()+"")+" 00:00:00";
            String date_2 = Valid.SetTgl(DTPCari2.getSelectedItem()+"")+" 23:59:59";
            String search = TCari.getText();
            String status = "", status_compile_filter, status_verifikator_filter;
            
            switch (cmbStatus.getSelectedItem().toString()) {
                case "Semua":
                    status = "";
                    break;
                case "Belum":
                    status = " AND idrg.status_coding = 'N' ";
                    break;
                case "Sudah":
                    status = " AND idrg.status_coding = 'Y' ";
                    break;
                default:
                    //throw new AssertionError();
                    status = " ";
            }
            
            switch (cmbStatusCompile.getSelectedItem().toString()) {
                case "Semua":
                    status_compile_filter = "";
                    break;
                case "Belum":
                    status_compile_filter = " AND idrg.status_compile = 'N' ";
                    break;
                case "Sudah":
                    status_compile_filter = " AND idrg.status_compile = 'Y' ";
                    break;
                default:
                    //throw new AssertionError();
                    status_compile_filter = " ";
            }
            
            switch (cmbStatusVerifikator.getSelectedItem().toString()) {
                case "Semua":
                    status_verifikator_filter = "";
                    break;
                case "Belum":
                    status_verifikator_filter = " AND (idrg.status_verifikasi = 'N' OR idrg.status_verifikasi IS NULL) ";
                    break;
                case "Sudah":
                    status_verifikator_filter = " AND idrg.status_verifikasi = 'Y' ";
                    break;
                default:
                    //throw new AssertionError();
                    status_verifikator_filter = " ";
            }
            
            String query_tampil = "SELECT "+
                                    "  rp.no_rawat, "+
                                    "  rp.tgl_registrasi, "+
                                    "  IFNULL(bs.no_sep, 'Belum Ada') AS no_sep, "+
                                    "  IFNULL(nj.no_nota, 'Belum Ada') AS no_nota, "+
                                    "  IFNULL(skb.no_surat, 'Belum Ada') AS no_surat, "+
                                    "  rp.no_rkm_medis, "+
                                    "  p.nm_pasien, "+
                                    "  d.nm_dokter, "+
                                    "  poli.nm_poli, "+
                                    "  pj.png_jawab, "+
                                    "  IFNULL(skb.status, 'Belum Ada') AS status, "+
                                    "  skb.created_at, "+
                                    "  rp.status_lanjut, "+
                                    "  enrj.id_encounter, "+
                                    "  idrg.id_resume_idrg, "+
                                    "  idrg.status_verifikasi, "+
                                    "  idrg.status_coding, "+
                                    "  idrg.status_compile "+
                                    "FROM "+
                                    "  reg_periksa rp "+
                                    "  LEFT JOIN bridging_sep bs ON rp.no_rawat = bs.no_rawat "+
                                    "  LEFT JOIN nota_jalan nj ON rp.no_rawat = nj.no_rawat "+
                                    "  LEFT JOIN surat_kontrol_bpjs skb ON skb.no_rawat = rp.no_rawat "+
                                    "  LEFT JOIN pasien p ON rp.no_rkm_medis = p.no_rkm_medis "+
                                    "  LEFT JOIN dokter d ON rp.kd_dokter = d.kd_dokter "+
                                    "  LEFT JOIN poliklinik poli ON rp.kd_poli = poli.kd_poli "+
                                    "  LEFT JOIN penjab pj ON rp.kd_pj = pj.kd_pj "+
                                    "  LEFT JOIN satu_sehat_encounter enrj ON rp.no_rawat = enrj.no_rawat "+
                                    "  LEFT JOIN resume_idrg idrg ON rp.no_rawat = idrg.no_rawat "+
                                    "WHERE "+
                                    "  rp.tgl_registrasi BETWEEN '"+date_1+"' AND '"+date_2+"' AND "+
                                    "  rp.stts = 'Sudah'"+
                                    // "  rp.status_lanjut = 'Ralan' AND rp.stts = 'Sudah'"+
                                    // "  (rp.kd_pj = '001' OR rp.kd_pj = '21' OR rp.kd_pj = '22' OR rp.kd_pj = '30' OR rp.kd_pj = 'BP' OR rp.kd_pj = 'BPJ') "+
                                    "";
            String query_search = "AND (rp.no_rawat LIKE '%"+search+"%' "+
                                  "OR rp.no_rkm_medis LIKE '%"+search+"%' "+
                                  "OR p.nm_pasien LIKE '%"+search+"%' "+
                                  "OR d.nm_dokter LIKE '%"+search+"%' "+
                                  "OR poli.nm_poli LIKE '%"+search+"%' "+
                                  "OR pj.png_jawab LIKE '%"+search+"%') ";
            String query_sort = "ORDER BY bs.no_sep "+sortSep.getText()+" ";
            // System.out.println("query_tampil: "+query_tampil+query_search+status+query_sort);
            ps=koneksi.prepareStatement(query_tampil+query_search+status+status_compile_filter+status_verifikator_filter+query_sort);
            try {
                rs=ps.executeQuery();
                String status_verifikasi = "Belum Terverifikasi oleh Verifikator";
                String status_coding = "Belum Coding";
                String status_compile = "Belum Compile";
                while(rs.next()){
                    if(rs.getString("status_verifikasi") == null || rs.getString("status_verifikasi").equals("") || rs.getString("status_verifikasi").equals("N")){
                        status_verifikasi = "Belum Terverifikasi oleh Verifikator";
                    }else{
                        status_verifikasi = "Sudah Terverifikasi oleh Verifikator";
                    }
                    if(rs.getString("status_coding") == null || rs.getString("status_coding").equals("") || rs.getString("status_coding").equals("N")){
                        status_coding = "Belum Coding";
                    }else{
                        status_coding = "Sudah Coding";
                    }
                    if(rs.getString("status_compile") == null || rs.getString("status_compile").equals("") || rs.getString("status_compile").equals("N")){
                        status_compile = "Belum Compile";
                    }else{
                        status_compile = "Sudah Compile";
                    }
                    tabMode.addRow(new String[]{
                        rs.getString("no_rawat"),
                        rs.getString("tgl_registrasi"),
                        rs.getString("no_sep"),
                        rs.getString("no_nota"),
                        rs.getString("no_surat"),
                        rs.getString("no_rkm_medis"),
                        rs.getString("nm_pasien"),
                        rs.getString("nm_dokter"),
                        rs.getString("nm_poli"),
                        rs.getString("png_jawab"),
                        rs.getString("status_lanjut"),
                        rs.getString("id_encounter"),
                        rs.getString("status"),
                        status_verifikasi,
                        status_coding,
                        status_compile
                    });
                }
                
                // table autofit
                for (int col = 0; col < tbRalan.getColumnCount(); col++) {
                    TableColumn column = tbRalan.getColumnModel().getColumn(col);
                    int maxWidth = 50; // minimal lebar kolom

                    for (int row = 0; row < tbRalan.getRowCount(); row++) {
                        TableCellRenderer renderer = tbRalan.getCellRenderer(row, col);
                        Component comp = tbRalan.prepareRenderer(renderer, row, col);
                        maxWidth = Math.max(comp.getPreferredSize().width + 20, maxWidth);
                    }

                    column.setPreferredWidth(maxWidth);
                }
            } catch (Exception e) {
                System.out.println("Notifikasi : "+e);
            } finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
        }catch(Exception e){
            System.out.println("Notifikasi : "+e);
        }
    }
    
    private void tampil_ranap(){
        String search = TCari.getText();
        String status = "", status_compile_filter, status_verifikator_filter;
        String status_verifikasi = "Belum Terverifikasi oleh Verifikator";

        switch (cmbStatus.getSelectedItem().toString()) {
            case "Semua":
                status = "";
                break;
            case "Belum":
                status = " AND resume_idrg.status_coding = 'N' ";
                break;
            case "Sudah":
                status = " AND resume_idrg.status_coding = 'Y' ";
                break;
            default:
                //throw new AssertionError();
                status = " ";
        }

        switch (cmbStatusCompile.getSelectedItem().toString()) {
            case "Semua":
                status_compile_filter = "";
                break;
            case "Belum":
                status_compile_filter = " AND resume_idrg.status_compile = 'N' ";
                break;
            case "Sudah":
                status_compile_filter = " AND resume_idrg.status_compile = 'Y' ";
                break;
            default:
                //throw new AssertionError();
                status_compile_filter = " ";
        }
            
        switch (cmbStatusVerifikator.getSelectedItem().toString()) {
            case "Semua":
                status_verifikator_filter = "";
                break;
            case "Belum":
                status_verifikator_filter = " AND (resume_idrg.status_verifikasi = 'N' OR resume_idrg.status_verifikasi IS NULL) ";
                break;
            case "Sudah":
                status_verifikator_filter = " AND resume_idrg.status_verifikasi = 'Y' ";
                break;
            default:
                //throw new AssertionError();
                status_verifikator_filter = " ";
        }
            
        String query_ranap = "select \n" +
                                "  kamar_inap.no_rawat, \n" +
                                "  reg_periksa.no_rkm_medis, \n" +
                                "  pasien.nm_pasien, \n" +
                                "  pasien.alamat, \n" +
                                "  pasien.kd_kel, \n" +
                                "  pasien.kd_kec, \n" +
                                "  pasien.kd_kab, \n" +
                                "  pasien.kd_prop, \n" +
                                "  pasien.alamatpj, \n" +
                                "  pasien.kelurahanpj, \n" +
                                "  pasien.kecamatanpj, \n" +
                                "  pasien.kabupatenpj, \n" +
                                "  pasien.propinsipj, \n" +
                                "  IFNULL(bridging_sep.no_sep, 'Belum Ada') AS no_sep, "+
                                "  IFNULL(nota_inap.no_nota, 'Belum Ada') AS no_nota, "+
                                "  IFNULL(surat_kontrol_bpjs.no_surat, 'Belum Ada') AS no_surat, "+
                                "  reg_periksa.p_jawab, \n" +
                                "  reg_periksa.hubunganpj, \n" +
                                "  penjab.png_jawab, \n" +
                                "  concat(\n" +
                                "    kamar_inap.kd_kamar, ' ', bangsal.nm_bangsal\n" +
                                "  ) as kamar, \n" +
                                "  kamar_inap.trf_kamar, \n" +
                                "  kamar_inap.diagnosa_awal, \n" +
                                "  kamar_inap.diagnosa_akhir, \n" +
                                "  kamar_inap.tgl_masuk, \n" +
                                "  kamar_inap.jam_masuk, \n" +
                                "  if(\n" +
                                "    kamar_inap.tgl_keluar = '0000-00-00', \n" +
                                "    '', kamar_inap.tgl_keluar\n" +
                                "  ) as tgl_keluar, \n" +
                                "  if(\n" +
                                "    kamar_inap.jam_keluar = '00:00:00', \n" +
                                "    '', kamar_inap.jam_keluar\n" +
                                "  ) as jam_keluar, \n" +
                                "  kamar_inap.ttl_biaya, \n" +
                                "  kamar_inap.stts_pulang, \n" +
                                "  kamar_inap.lama, \n" +
                                "  dokter.nm_dokter, \n" +
                                "  kamar_inap.kd_kamar, \n" +
                                "  reg_periksa.kd_pj, \n" +
                                "  concat(\n" +
                                "    reg_periksa.umurdaftar, ' ', reg_periksa.sttsumur\n" +
                                "  ) as umur, \n" +
                                "  reg_periksa.status_bayar, \n" +
                                "  pasien.agama, \n" +
                                "  dpjp_ranap.kd_dokter, \n"+
                                "  satu_sehat_encounter_imp.id_encounter, \n"+
                                "  resume_idrg.id_resume_idrg, \n"+
                                "  resume_idrg.status_verifikasi, \n"+
                                "  resume_idrg.status_coding, \n"+
                                "  resume_idrg.status_compile \n"+
                                "from \n" +
                                "  kamar_inap \n" +
                                "  inner join reg_periksa on kamar_inap.no_rawat = reg_periksa.no_rawat \n" +
                                "  inner join pasien on reg_periksa.no_rkm_medis = pasien.no_rkm_medis \n" +
                                "  inner join kamar on kamar_inap.kd_kamar = kamar.kd_kamar \n" +
                                "  inner join bangsal on kamar.kd_bangsal = bangsal.kd_bangsal \n" +
                                "  left join dpjp_ranap on kamar_inap.no_rawat = dpjp_ranap.no_rawat AND dpjp_ranap.`status` = 'Utama' \n" +
                                "  left join dokter on dpjp_ranap.kd_dokter = dokter.kd_dokter \n" +
                                "  left join penjab on reg_periksa.kd_pj = penjab.kd_pj \n" +
                                "  left join bridging_sep on kamar_inap.no_rawat = bridging_sep.no_rawat \n" +
                                "  left join nota_inap on kamar_inap.no_rawat = nota_inap.no_rawat \n" +
                                "  left join satu_sehat_encounter_imp on kamar_inap.no_rawat = satu_sehat_encounter_imp.no_rawat \n" +
                                "  left join surat_kontrol_bpjs on kamar_inap.no_rawat = surat_kontrol_bpjs.no_rawat \n" +
                                "  left join resume_idrg on reg_periksa.no_rawat = resume_idrg.no_rawat \n" +
                                "where kamar_inap.tgl_keluar between '"+Valid.SetTgl(DTPCari1.getSelectedItem()+"")+"' and '"+Valid.SetTgl(DTPCari2.getSelectedItem()+"")+
                                "' and reg_periksa.status_bayar like '%%' ";
        
        String query_search = "AND (reg_periksa.no_rawat LIKE '%"+search+"%' "+
                                "OR reg_periksa.no_rkm_medis LIKE '%"+search+"%' "+
                                "OR pasien.nm_pasien LIKE '%"+search+"%' "+
                                "OR dokter.nm_dokter LIKE '%"+search+"%' "+
                                "OR kamar.kd_kamar LIKE '%"+search+"%' "+
                                "OR bangsal.nm_bangsal LIKE '%"+search+"%' "+
                                "OR penjab.png_jawab LIKE '%"+search+"%') ";
        
        String query_sort = "ORDER BY bridging_sep.no_sep "+sortSep.getText()+" ";
        try {
            ps=koneksi.prepareStatement(query_ranap+query_search+status+status_compile_filter+status_verifikator_filter+query_sort);
            // ps=koneksi.prepareStatement(query_tampil+query_search+status+status_compile_filter+query_sort);
            System.out.println(ps.toString());
            try {
                rs=ps.executeQuery();
                while(rs.next()){
                    //ps_satu_sehat_detail_pasien = koneksi.prepareStatement("SELECT province_name, city_name, district_name, village_name, province_name_pj, city_name_pj, district_name_pj, village_name_pj, ihs_number, postal_code, id_rw, id_rt, rw_pj, rt_pj, emergency_contact FROM satu_sehat_pasien WHERE no_rkm_medis = '"+rs.getString("no_rkm_medis")+"'");
                    //rs_satu_sehat_detail_pasien = ps_satu_sehat_detail_pasien.executeQuery();
                    //if(rs_satu_sehat_detail_pasien.next()){
                    //    village = rs_satu_sehat_detail_pasien.getString("village_name");
                    //    district = rs_satu_sehat_detail_pasien.getString("district_name");
                    //    city = rs_satu_sehat_detail_pasien.getString("city_name");
                    //    province = rs_satu_sehat_detail_pasien.getString("province_name");
                    //    village_pj = rs_satu_sehat_detail_pasien.getString("village_name_pj");
                    //    district_pj = rs_satu_sehat_detail_pasien.getString("district_name_pj");
                    //    city_pj = rs_satu_sehat_detail_pasien.getString("city_name_pj");
                    //    province_pj = rs_satu_sehat_detail_pasien.getString("province_name_pj");
                    //    detail_alamat_pasien = village+", "+district+", "+city+", "+province;
                    //    detail_alamat_pj = village_pj+", "+district_pj+", "+city_pj+", "+province_pj;
                    //    id_kel=rs.getString("kd_kel");
                    //    id_kec=rs.getString("kd_kec");
                    //    id_kab=rs.getString("kd_kab");
                    //    id_prov=rs.getString("kd_prop");
                    //    id_kel_pj=rs.getString("kelurahanpj");
                    //    id_kec_pj=rs.getString("kecamatanpj");
                    //    id_kab_pj=rs.getString("kabupatenpj");
                    //    id_prov_pj=rs.getString("propinsipj");
                    //    postal_code=rs_satu_sehat_detail_pasien.getString("postal_code");
                    //    id_rw=rs_satu_sehat_detail_pasien.getString("id_rw");
                    //    id_rt=rs_satu_sehat_detail_pasien.getString("id_rt");
                    //    rw_pj=rs_satu_sehat_detail_pasien.getString("rw_pj");
                    //    rt_pj=rs_satu_sehat_detail_pasien.getString("rt_pj");
                    //    emergency_contact=rs_satu_sehat_detail_pasien.getString("emergency_contact");
                    //}else{
                    //    village = Sequel.cariIsi("SELECT nm_kel FROM kelurahan WHERE kd_kel = '"+rs.getString("kd_kel")+"'");
                    //    district = Sequel.cariIsi("SELECT nm_kec FROM kecamatan WHERE kd_kec = '"+rs.getString("kd_kec")+"'");
                    //    city = Sequel.cariIsi("SELECT nm_kab FROM kabupaten WHERE kd_kab = '"+rs.getString("kd_kab")+"'");
                    //    province = Sequel.cariIsi("SELECT nm_prop FROM propinsi WHERE kd_prop = '"+rs.getString("kd_prop")+"'");
                    //    detail_alamat_pasien = village+", ";
                    //    detail_alamat_pasien += district+", ";
                    //    detail_alamat_pasien += city+", ";
                    //    detail_alamat_pasien += province;
                    //    village_pj = rs.getString("kelurahanpj");
                    //    district_pj = rs.getString("kecamatanpj");
                    //    city_pj = rs.getString("kabupatenpj");
                    //    province_pj = rs.getString("propinsipj");
                    //    id_kel=rs.getString("kd_kel");
                    //    id_kec=rs.getString("kd_kec");
                    //    id_kab=rs.getString("kd_kab");
                    //    id_prov=rs.getString("kd_prop");
                    //    id_kel_pj="-";
                    //    id_kec_pj="-";
                    //    id_kab_pj="-";
                    //    id_prov_pj="-";
                    //    postal_code="-";
                    //    id_rw="-";
                    //    id_rt="-";
                    //    rw_pj="-";
                    //    rt_pj="-";
                    //    emergency_contact="-";
                    //}
                    String sudah_coding = "Belum";
                    if(rs.getString("status_coding") != null && rs.getString("status_coding").equals("Y")){
                        sudah_coding = "Sudah Coding";
                    }else{
                        sudah_coding = "Belum Coding";
                    }
                    String sudah_compile = "Belum";
                    if(rs.getString("status_compile") != null && rs.getString("status_compile").equals("Y")){
                        sudah_compile = "Sudah Compile";
                    }else{
                        sudah_compile = "Belum Compile";
                    }
                    if(rs.getString("status_verifikasi") == null || rs.getString("status_verifikasi").equals("") || rs.getString("status_verifikasi").equals("N")){
                        status_verifikasi = "Belum Terverifikasi oleh Verifikator";
                    }else{
                        status_verifikasi = "Sudah Terverifikasi oleh Verifikator";
                    }
                    tabMode2.addRow(new String[]{
                        rs.getString("no_rawat"),
                        rs.getString("tgl_keluar"),
                        rs.getString("no_sep"),
                        rs.getString("no_nota"),
                        rs.getString("no_surat"),
                        rs.getString("no_rkm_medis"),
                        rs.getString("nm_pasien"),
                        rs.getString("nm_dokter"),
                        rs.getString("kamar"),
                        rs.getString("png_jawab"),
                        rs.getString("stts_pulang"),
                        rs.getString("id_encounter"),
                        rs.getString("status_bayar"),
                        status_verifikasi,
                        sudah_coding,
                        sudah_compile
                    });
                }

                // table autofit
                for (int col = 0; col < tbRanap.getColumnCount(); col++) {
                    TableColumn column = tbRanap.getColumnModel().getColumn(col);
                    int maxWidth = 50; // minimal lebar kolom

                    for (int row = 0; row < tbRanap.getRowCount(); row++) {
                        TableCellRenderer renderer = tbRanap.getCellRenderer(row, col);
                        Component comp = tbRanap.prepareRenderer(renderer, row, col);
                        maxWidth = Math.max(comp.getPreferredSize().width + 10, maxWidth);
                    }

                    column.setPreferredWidth(maxWidth);
                }
            } catch (Exception e) {
                System.out.println("Notifikasi : "+e);
            } finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(DlgIDRG.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void getData() {
        int row=tbRalan.getSelectedRow();
        if(row!= -1){
//            String id=tabMode.getValueAt(row,0).toString();
//            String ip_address=tabMode.getValueAt(row,1).toString();
//            String workstation=tabMode.getValueAt(row,2).toString();
//            txtNorawat.setText(id);
//            txtNoNota.setText(workstation);
//            txtNoSurat.setText(ip_address);
        }
    }
    
    public void setData(String no_rawat){
        txtNorawat.setText(no_rawat);
        tampil();
    }

    public void emptTeks() {
        txtNorawat.setText("");
        txtNoNota.setText("");
        txtNoRm.setText("");
        txtNoNota.requestFocus();
    }
    
    public JTable getTable(){
        return tbRalan;
    }
}
